In [1]:
import numpy as np
np.__version__

'1.22.3'

In [2]:
np.array([1,2,"1"])

array(['1', '2', '1'], dtype='<U11')

In [3]:
x = np.array([1,2,"1"])

In [4]:
x.dtype

dtype('<U11')

In [5]:
type(x)

numpy.ndarray

In [6]:
class_list = [1,2,3,4,5]

In [7]:
type(class_list)

list

In [8]:
numpy_array = np.array(class_list)
type(numpy_array)

numpy.ndarray

In [9]:
numpy_array.shape

(5,)

In [10]:
np.array([2,5]).mean()

3.5

In [11]:
np.array([2,6]).std()

2.0

In [12]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [13]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [14]:
matrix1[0,:]

array([1, 2, 3])

In [15]:
matrix1[:,2]

array([3, 6, 9])

In [16]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [17]:
matrix2.sum()

47

In [18]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [19]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [20]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [21]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

In [22]:
wek1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [24]:
wek2 = np.repeat(1,10)

In [25]:
wek1 + wek2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
macierz = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
macierz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
macierz.shape

(5, 5)

In [28]:
macierz.sum()

325

In [29]:
macierz[0,:].mean()

3.0

In [30]:
macierz[1,:].mean()

8.0

In [31]:
for i in range(0,5):
    print(macierz[i,:].mean())

3.0
8.0
13.0
18.0
23.0


In [32]:
for i in range(0,5):
    print(macierz[:,i].mean())

11.0
12.0
13.0
14.0
15.0
